services:
  # Serviço do MongoDB
  mongodb:
    image: mongo:6
    container_name: todos-mongodb
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: senha123
      MONGO_INITDB_DATABASE: todosdb
    volumes:
      - mongodb_data:/data/db
    networks:
      - todos-network

  # Serviço da aplicação Node.js (Backend)
  todos-backend:
    build: ./server
    container_name: todos-backend
    restart: always
    ports:
      - "5000:5000"
    environment:
      PORT: 5000
      MONGODB_URI: mongodb://admin:senha123@mongodb:27017/todosdb?authSource=admin
    depends_on:
      - mongodb
    networks:
      - todos-network
    volumes:
      - ./server:/app
      - /app/node_modules

  # Serviço do Frontend React
  frontend:
    build: ./client
    container_name: todos-frontend
    restart: always
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_URL=http://172.172.133.83:5000
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true
    depends_on:
      - todos-backend
    networks:
      - todos-network
    volumes:
      - ./client:/app
      - /app/node_modules
    stdin_open: true
    tty: true

# Volume para persistir os dados do MongoDB
volumes:
  mongodb_data:

# Rede para comunicação entre os containers
networks:
  todos-network:
    driver: bridge